#!/usr/bin/env python3
"""Offline doc generator for houdini-bridge-mcp.

Single source of truth = `reference/catalog.json`, the typed tool catalog dumped
straight from the Rust security boundary (`gateway/src/tools.rs`) by
`cargo test emit_catalog_json`. This script never re-parses the .rs; it consumes
that authoritative JSON, so every doc it emits is provably whatever the compiled
boundary contains.

Modes (compose freely; default = all):
  --params     regenerate docs/_TOOL_PARAMS.md   (the flat, exact param cheat-sheet)
  --readme     regenerate the tool tables in README.md between the TOOLS markers
  --check      NON-DESTRUCTIVE: assert the README tables' tool set == the catalog
               (the drift guard; exits non-zero on any mismatch)
  --coverage   annotate reference/NODE_REFERENCE.md with per-node :tool= / :UNEXPOSED
  --refresh    run `cargo test emit_catalog_json` first to refresh catalog.json

Run from anywhere; paths resolve relative to the repo root (this file's parent's
parent).
"""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "reference" / "catalog.json"
TOOL_PARAMS = REPO / "docs" / "_TOOL_PARAMS.md"
README = REPO / "README.md"
NODE_REFERENCE = REPO / "reference" / "NODE_REFERENCE.md"
TOOL_NODES = REPO / "reference" / "tool_nodes.json"
HOUDINI_NODES = REPO / "reference" / "houdini_nodes.json"

# COP section markers in NODE_REFERENCE.md (idempotent regen block).
COP_BEGIN = "<!-- BEGIN COP (generated) -->"
COP_END = "<!-- END COP (generated) -->"

# Category display order (must match the README section order).
CATEGORY_ORDER = [
    "Acquire & import",
    "Terrain & heightfields",
    "Model & geometry",
    "Groups & attributes",
    "Cleanup & meshing",
    "Instance & scatter",
    "VDB & volumes",
    "Solvers & simulation",
    "KineFX",
    "Crowd",
    "Muscle",
    "VEX (validated safe-VEX)",
    "ML / ONNX inference",
    "Copernicus / COP",
    "Image / texture",
    "Solaris / LOP / USD",
    "Look, lights & camera",
    "Scene, navigation & viewport",
    "Parameters",
    "Deliver & export",
    "Render & output (WIRE-ONLY)",
]

GEN_WARNING = "<!-- GENERATED by scripts/generate_docs.py from reference/catalog.json — do not hand-edit. -->"


# --------------------------------------------------------------------------- io
def load_catalog() -> dict:
    if not CATALOG.exists():
        sys.exit(f"catalog not found: {CATALOG}\n  run: cargo test emit_catalog_json  (in gateway/)")
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    tools = data["tools"]
    # Stable: preserve catalog (batch) order within each category.
    for i, t in enumerate(tools):
        t["_ord"] = i
        if not t.get("category"):
            sys.exit(f"tool '{t['name']}' has no category — re-run the category dump.")
        if t["category"] not in CATEGORY_ORDER:
            sys.exit(f"tool '{t['name']}' has unknown category '{t['category']}'.")
    return data


def by_category(tools: list[dict]) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {c: [] for c in CATEGORY_ORDER}
    for t in tools:
        out[t["category"]].append(t)
    for c in out:
        out[c].sort(key=lambda t: t["_ord"])
    return out


def refresh_catalog() -> None:
    print("refreshing catalog.json via cargo test emit_catalog_json ...")
    subprocess.run(
        ["cargo", "test", "emit_catalog_json", "--", "--nocapture"],
        cwd=REPO / "gateway", check=True,
    )


# ------------------------------------------------------------------ rendering
def render_kind(p: dict) -> str:
    """Exact typed rendering of one param's kind (as declared in the boundary)."""
    k = p["kind"]
    if k in ("Str", "NodePath", "Bool"):
        return k
    if k == "FsPath":
        return "FsPath write" if p.get("write") else "FsPath read"
    if k == "Int":
        return f"Int {p['min']}..{p['max']}"
    if k == "Num":
        return f"Num {fmtnum(p['min'])}..{fmtnum(p['max'])}"
    if k == "Enum":
        return "Enum: " + "|".join(p["choices"])
    if k == "NumVec":
        return f"NumVec[{p['len']}]"
    return k


def fmtnum(x) -> str:
    if isinstance(x, float) and x.is_integer():
        return str(int(x))
    return str(x)


def md_escape_pipe(s: str) -> str:
    return s.replace("|", r"\|")


# ------------------------------------------------------------------- _TOOL_PARAMS
def gen_params(data: dict) -> str:
    tools = data["tools"]
    buckets = by_category(tools)
    out: list[str] = []
    out.append("# Houdini MCP — Tool Parameter Cheat-Sheet")
    out.append("")
    out.append(GEN_WARNING)
    out.append("")
    out.append(
        "**Exact param reference, generated from `gateway/src/tools.rs` (the typed catalog / "
        "security boundary) via `reference/catalog.json`.** Param names, types, required/optional, "
        "ranges, and enum tokens are exactly as declared — pass them verbatim over MCP."
    )
    out.append("")
    out.append(f"**{len(tools)} tools.**")
    out.append("")
    out.append("**How to read the types**")
    out.append("- `Str` — non-empty string when required.")
    out.append("- `NodePath` — a Houdini node path string (e.g. `/obj/foo/OUT`); NOT filesystem-confined; for `input`-style params the node generally must already exist.")
    out.append("- `FsPath read` — filesystem path, `realpath`-confined to the working dir; the file must already exist.")
    out.append("- `FsPath write` — filesystem path confined to the working dir; a not-yet-existing leaf is allowed (parent chain still confined).")
    out.append("- `Int min..max` / `Num min..max` — numerics are **clamped** into range, not rejected.")
    out.append("- `Bool` — true/false.")
    out.append("- `Enum: a|b|c` — must be one of the listed tokens exactly.")
    out.append("- `NumVec[len]` — a JSON array of exactly `len` finite numbers.")
    out.append("")
    out.append(
        "The validation gate rejects unknown params, enforces required params, and confines all "
        "`FsPath`s. There is deliberately no arbitrary-code / generic-node / raw-VEX tool."
    )
    out.append("")
    for cat in CATEGORY_ORDER:
        group = buckets[cat]
        if not group:
            continue
        out.append("---")
        out.append("")
        out.append(f"## {cat}")
        out.append("")
        for t in group:
            out.append(f"### {t['name']}")
            out.append(t["description"])
            if not t["params"]:
                out.append("- (no params)")
            else:
                for p in t["params"]:
                    req = "**required**" if p["required"] else "optional"
                    desc = p.get("desc", "").strip()
                    tail = f" — {desc}" if desc else ""
                    out.append(f"- `{p['name']}` ({render_kind(p)}, {req}){tail}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


# ----------------------------------------------------------------------- README
BEGIN = "<!-- BEGIN TOOLS (generated) -->"
END = "<!-- END TOOLS (generated) -->"


def gen_readme_tables(data: dict) -> str:
    """The tool-catalog block that lives between the BEGIN/END markers."""
    tools = data["tools"]
    buckets = by_category(tools)
    out: list[str] = [BEGIN, GEN_WARNING, ""]
    for cat in CATEGORY_ORDER:
        group = buckets[cat]
        if not group:
            continue
        out.append(f"### {cat}")
        out.append("")
        out.append("| Tool | What it does | Key params |")
        out.append("|---|---|---|")
        for t in group:
            desc = first_sentence(t["description"])
            req = [p["name"] for p in t["params"] if p["required"]]
            n_opt = sum(1 for p in t["params"] if not p["required"])
            if req:
                key = ", ".join(f"`{n}`" for n in req)
                if n_opt:
                    key += f" (+{n_opt} optional)"
            elif n_opt:
                key = f"{n_opt} optional"
            else:
                key = "—"
            out.append(f"| `{t['name']}` | {md_escape_pipe(desc)} | {md_escape_pipe(key)} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def first_sentence(s: str) -> str:
    s = s.strip()
    # Split on the first sentence-ending period followed by a space + capital, or end.
    depth = 0
    for i in range(len(s) - 1):
        c = s[i]
        if c == "(":
            depth += 1
            continue
        if c == ")":
            depth = max(0, depth - 1)
            continue
        if depth == 0 and c == "." and (i + 1 >= len(s) or s[i + 1] == " "):
            # Never split inside a parenthetical (e.g. an "(e.g. ...)" / "(0 uniform, ...)"
            # clause), nor on decimals / abbreviations where the next word is lowercase.
            if i + 2 < len(s) and s[i + 2].islower():
                continue
            return s[: i + 1]
    return s


def write_readme(data: dict) -> None:
    text = README.read_text(encoding="utf-8")
    block = gen_readme_tables(data)
    if BEGIN in text and END in text:
        pre = text[: text.index(BEGIN)]
        post = text[text.index(END) + len(END):]
        README.write_text(pre + block + post, encoding="utf-8")
        print(f"README.md: replaced tool tables ({len(data['tools'])} tools).")
    else:
        sys.exit(
            "README.md has no BEGIN/END TOOLS markers.\n"
            "  Add these two lines around the tool-catalog block, then re-run --readme:\n"
            f"    {BEGIN}\n    ...tables...\n    {END}"
        )


# ------------------------------------------------------------------------ check
def check_readme(data: dict) -> int:
    """Non-destructive drift guard: README table tool set must equal the catalog."""
    import re
    catalog_names = {t["name"] for t in data["tools"]}
    text = README.read_text(encoding="utf-8")
    # Tool rows: | `name` | ... | ; skip config/other tables (name must be in catalog-shape).
    readme_names = set(re.findall(r"^\|\s*`([a-z0-9_]+)`\s*\|", text, re.M))
    # Restrict to plausible tool rows by intersect-or-report.
    missing = catalog_names - readme_names          # in boundary, undocumented
    extra = readme_names - catalog_names            # documented, not in boundary
    # `extra` may include non-tool backticked first cells; report them so a human can judge.
    if not missing and not extra:
        print(f"README drift check OK - {len(catalog_names)} tools, README in sync.")
        return 0
    if missing:
        print(f"DRIFT: {len(missing)} catalog tool(s) NOT documented in README: {sorted(missing)}")
    if extra:
        print(f"DRIFT: {len(extra)} README table name(s) NOT in catalog: {sorted(extra)}")
    return 1


# ----------------------------------------------------------------- node-doc (COP)
def _is_scalar_default(d) -> bool:
    return isinstance(d, (bool, int, float, str)) and not isinstance(d, list)


def _fmt_default(d) -> str:
    if isinstance(d, bool):
        return "true" if d else "false"
    return str(d)


def node_param_line(node: str, o: dict) -> str:
    """One `[node] param :type ...` line — identical grammar to the SOP/OBJ/LOP bodies
    (ported from the established node-doc generator so COP lines match byte-for-byte)."""
    typ = (o.get("type", "unknown") or "unknown").lower()
    menu = o.get("menu")
    if menu:
        toks = [str(t) for t in menu]
        if len(toks) > 24:
            toks = toks[:24] + ["..."]
        menustr = ":menu(%s)" % "|".join(toks)
    else:
        menustr = None
    if typ == "menu":
        line = "[%s] %s %s" % (node, o["name"], menustr if menustr else ":menu")
    else:
        line = "[%s] %s :%s" % (node, o["name"], typ)
        if menustr:
            line += " " + menustr
    c = o.get("components")
    if isinstance(c, int) and c > 1:
        line += " :vec%d" % c
    if "min" in o and "max" in o:
        line += " :range(%s..%s)" % (fmtnum(o["min"]), fmtnum(o["max"]))
    d = o.get("default")
    if _is_scalar_default(d):
        line += " :def=%s" % _fmt_default(d)
    return line


def build_cop_block() -> tuple[str, int]:
    """The regenerated `## COP` section (between COP_BEGIN/COP_END), sourced from
    houdini_nodes.json's `Cop` category. Returns (block_text, node_count)."""
    if not HOUDINI_NODES.exists():
        sys.exit(f"houdini_nodes.json not found: {HOUDINI_NODES}")
    nodes_data = json.loads(HOUDINI_NODES.read_text(encoding="utf-8"))
    cop_types = sorted(nodes_data.get("node_types", {}).get("Cop", []), key=str.lower)
    params = nodes_data.get("params", {})

    def cop_params(name):
        """Cop params for a node: prefer the category-suffixed "<name> (Cop)" key
        (present when the plain name collides with a non-Cop category and now holds
        that non-Cop version), else fall back to the plain name."""
        return params.get(name + " (Cop)") or params.get(name)

    cop_types = [n for n in cop_types if cop_params(n)]  # only nodes with probed params
    out: list[str] = [COP_BEGIN, GEN_WARNING, "", "## COP", ""]
    out.append(
        "The Copernicus (COP) 2D image lane, category `Cop` (H20.5+). Live-probed on "
        "**21.0.671**, same grammar as the sections above. Serve params for any of these via "
        "`node_reference(node=\"<name>\", category=\"Cop\")`."
    )
    out.append("")
    out.append("**Index (%d nodes):** %s" % (len(cop_types), ", ".join(cop_types)))
    out.append("")
    for node in cop_types:
        out.append("### %s  (Cop)" % node)
        for o in cop_params(node):
            out.append(node_param_line(node, o))
        out.append("")
    out.append(COP_END)
    return "\n".join(out).rstrip() + "\n", len(cop_types)


def emit_cop_section() -> int:
    """Insert/refresh the COP section in NODE_REFERENCE.md and add COP to the Categories
    index. Idempotent: replaces the marked block if present, else appends it."""
    block, n_cop = build_cop_block()
    text = NODE_REFERENCE.read_text(encoding="utf-8")

    if COP_BEGIN in text and COP_END in text:
        pre = text[: text.index(COP_BEGIN)]
        post = text[text.index(COP_END) + len(COP_END):]
        text = pre.rstrip() + "\n\n" + block + post
    else:
        text = text.rstrip() + "\n\n" + block

    # Add a COP link to the `## Categories` jump line (idempotent).
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("[SOP](#sop)") and "[COP](#cop)" not in line:
            lines[i] = line.rstrip() + " | [COP](#cop)"
            break
    text = "\n".join(lines)
    if not text.endswith("\n"):
        text += "\n"

    NODE_REFERENCE.write_text(text, encoding="utf-8")
    print(f"NODE_REFERENCE.md: emitted COP section ({n_cop} Cop nodes).")
    return n_cop


# --------------------------------------------------------------------- coverage
def gen_coverage(data: dict) -> int:
    """Annotate NODE_REFERENCE.md with per-node coverage flags from tool_nodes.json."""
    if not TOOL_NODES.exists():
        sys.exit(
            f"{TOOL_NODES} not found — the endpoint->nodetype map is required for --coverage.\n"
            "  (Build it first; see the generator notes.)"
        )
    import re
    nmap = json.loads(TOOL_NODES.read_text(encoding="utf-8"))
    catalog_names = {t["name"] for t in data["tools"]}
    # Build (category, nodetype) -> [tools]. Keys are normalized (strip OBJ:/OUT: prefixes).
    # A tool entry MAY declare "category" (e.g. "Cop") to disambiguate same-named nodes
    # across categories (COP `bend` vs SOP `bend`); legacy entries have no category.
    node_to_tools: dict[tuple[str | None, str], set[str]] = {}
    declared_categories: set[str] = set()
    unmapped_tools = catalog_names - set(nmap.get("tools", {}))
    for tool, info in nmap.get("tools", {}).items():
        cat = info.get("category")  # None for legacy (category-agnostic) entries
        if cat:
            declared_categories.add(cat)
        for nt in info.get("nodes", []):
            node_to_tools.setdefault((cat, norm_nt(nt)), set()).add(tool)

    def tools_for(name: str, heading_cat: str) -> set[str]:
        # category-specific matches (tool declared this exact category)...
        matched = set(node_to_tools.get((heading_cat, name), set()))
        # ...plus legacy (untagged) matches, EXCEPT for categories that are fully
        # declared elsewhere (e.g. once any COP tool carries category="Cop", untagged
        # entries must not bleed onto COP headings).
        if heading_cat not in declared_categories:
            matched |= node_to_tools.get((None, name), set())
        return matched

    lines = NODE_REFERENCE.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    heading_re = re.compile(r"^### (\S+)\s+\((.+)\)\s*$")
    annotated = covered = unexposed = 0
    i = 0
    while i < len(lines):
        line = lines[i]
        m = heading_re.match(line)
        out.append(line)
        if m:
            key = m.group(1)
            tools = tools_for(norm_nt(key), m.group(2).strip())
            # drop any pre-existing annotation line right after the heading
            if i + 1 < len(lines) and lines[i + 1].startswith("> coverage:"):
                i += 1  # skip old annotation
            if tools:
                covered += 1
                out.append("> coverage: :tool=" + ",".join(sorted(tools)))
            else:
                unexposed += 1
                out.append("> coverage: :UNEXPOSED")
            annotated += 1
        i += 1
    NODE_REFERENCE.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"NODE_REFERENCE.md: annotated {annotated} nodes ({covered} covered, {unexposed} unexposed).")
    if unmapped_tools:
        print(f"  NOTE: {len(unmapped_tools)} catalog tool(s) absent from tool_nodes.json: {sorted(unmapped_tools)}")
    return 0


def norm_nt(nt: str) -> str:
    for pre in ("OBJ:", "OUT:", "SOP:", "LOP:"):
        if nt.startswith(pre):
            return nt[len(pre):]
    return nt


# --------------------------------------------------------------------------- cli
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--params", action="store_true")
    ap.add_argument("--readme", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--coverage", action="store_true")
    ap.add_argument("--nodedoc", action="store_true",
                    help="emit/refresh the COP section in NODE_REFERENCE.md from houdini_nodes.json")
    ap.add_argument("--refresh", action="store_true")
    args = ap.parse_args()

    if args.refresh:
        refresh_catalog()

    data = load_catalog()
    do_all = not (args.params or args.readme or args.check or args.coverage or args.nodedoc)
    rc = 0

    if args.params or do_all:
        TOOL_PARAMS.write_text(gen_params(data), encoding="utf-8")
        print(f"docs/_TOOL_PARAMS.md: regenerated ({len(data['tools'])} tools).")
    if args.check or do_all:
        rc |= check_readme(data)
    if args.readme:  # destructive — opt-in only, never in the default set
        write_readme(data)
    # Emit the COP node bodies before coverage so the join has (Cop) headings to annotate.
    if args.nodedoc or args.coverage or do_all:
        emit_cop_section()
    if args.coverage or do_all:
        if TOOL_NODES.exists():
            gen_coverage(data)
        elif not do_all:
            gen_coverage(data)  # explicit --coverage without the map -> error
        else:
            print("skipping --coverage: reference/tool_nodes.json not present yet.")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
